#!/bin/bash
BASE_DIR="../../"
TEMP_DIR="$BASE_DIR/setup/tests/arch/temp"
mkdir $TEMP_DIR
#IP=$(ifconfig en0 | grep inet | awk '$1=="inet" {print $2}')
#xhost + $IP

cp -r "$BASE_DIR/.config" $TEMP_DIR/
cp "$BASE_DIR/setup/arch-bootstrap.sh" $TEMP_DIR/
cp "$BASE_DIR/setup/dependencies.yaml" $TEMP_DIR/
cp "$BASE_DIR/setup/fabfile.py" $TEMP_DIR/
cp "$BASE_DIR/setup/utilities.py" $TEMP_DIR/

#chmod +x ./arch/arch-bootstrap.sh
docker build -t kian/arch.dotfiles ./arch
rm -rf $TEMP_DIR
docker run \
  --rm \
  -it kian/arch.dotfiles
# -v /tmp/.X11-unix:/tmp/.X11-unix \
